---
displayName: NodeJS Express
description: NodeJS stack with NPM 6.13.4, NodeJS 10.19.0 and Express Web Application
tags: ["NodeJS", "NPM", "Express", "UBI8"]
icon: /images/type-node.svg
globalMemoryLimit: 2198Mi
