---
displayName: C/C++
description: C and C++ Developer Tools stack with GCC 8.3.1, cmake 3.11.4 and make 4.2.1 
tags: ["UBI8", "C", "C++", "clang", "GCC", "g++", "make", "cmake"]
icon: /images/type-cpp.svg
globalMemoryLimit: 1686Mi
