---
displayName: Java EAP XP Microprofile
description: Java stack with EAP XP 1.0, OpenJDK 11 and Maven 3.5
tags: ["RHEL8", "Java", "OpenJDK", "Maven", "EAP", "Microprofile"]
icon: /images/type-jboss.svg
globalMemoryLimit: 3186Mi
