#
# Copyright IBM Corporation 2020-2021
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   IBM Corporation - implementation
#

displayName: Wazi Developer
description: IBM Z Open Editor 1.2.0 with IBM Z Enterprise COBOL 6.3, PL/I 5.3, HLASM 2.4, TSO/E REXX, Zowe Explorer 1.12.1, IBM Z Open Debug 1.1.1
tags: ["COBOL", "PL/I", "PLI", "PL1", "HLASM", "JCL", "IDE", "LSP", "language-server", "z/OS", "zOS", "IBM Z", "Z Software", "Zowe", "Mainframe", "REXX", "Debug"]
icon: /images/type-wazi.svg
globalMemoryLimit: 3000Mi
