---
displayName: Java Quarkus
description: Java stack with Quarkus Tools, Gradle 6.1 and Maven 3.6.3
tags: ["Java", "Quarkus", "Maven", "Gradle", "UBI8"]
icon: /images/type-quarkus.svg
globalMemoryLimit: 2674Mi
