---
displayName: Java with JBoss EAP 7.3
description: Java stack with OpenJDK 8, Maven 3.5 and JBoss EAP 7.3
tags: ["Java", "OpenJDK", "Maven", "EAP", "RHEL7"]
icon: /images/type-jboss.svg
globalMemoryLimit: 3698Mi
