---
displayName: Java with JBoss EAP XP 2.0 Bootable Jar
description: Java stack with OpenJDK 11, Maven 3.6.3 and JBoss EAP XP 2.0 Bootable Jar
tags: ["RHEL8", "Java", "OpenJDK", "Maven", "EAP", "Microprofile", "EAP XP", "Bootable Jar"]
icon: /images/type-jboss.svg
globalMemoryLimit: 3698Mi
