#
# Copyright IBM Corporation 2020-2021
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   IBM Corporation - implementation
#

displayName: Wazi Developer with sample apps
description: COBOL, PL/I, HLASM, REXX stack for IBM Z Open Editor 1.4.0, IBM Z Open Debug 1.4.0, Zowe Explorer 1.19.0, Zowe CLI 6.33.3
tags: ["COBOL", "PL/I", "PLI", "PL1", "HLASM", "JCL", "IDE", "LSP", "language-server", "z/OS", "zOS", "IBM Z", "Z Software", "Zowe", "Mainframe", "REXX", "Debug"]
icon: /images/type-wazi.svg
