---
displayName: Java Lombok
description: Java stack with Lombok 1.18.18, OpenJDK 11 and Maven 3.6.3
tags: ["RHEL8", "Java", "OpenJDK", "Maven", "Lombok"]
icon: /images/type-lombok.svg
globalMemoryLimit: 3186Mi
