---
displayName: Java Quarkus
description: Java stack with OpenJDK 11, Maven 3.6.3, Gradle 6.1 and Quarkus Tools
tags: ["Java", "OpenJDK", "Maven", "Gradle", "Quarkus", "UBI8"]
icon: /images/type-quarkus.svg
globalMemoryLimit: 2674Mi
