---
displayName: Red Hat Fuse
description: Red Hat Fuse stack with OpenJDK 8 and Maven 3.6.3
tags: ["RHEL8", "Java", "OpenJDK", "Maven", "Red Hat Fuse"]
icon: /images/type-fuse.svg
globalMemoryLimit: 2816Mi
