---
displayName: Java with JBoss EAP XP 2.0 Microprofile
description: Java stack with OpenJDK 11, Maven 3.5.4 and JBoss EAP XP 2.0
tags: ["RHEL8", "Java", "OpenJDK", "Maven", "EAP", "Microprofile", "EAP XP"]
icon: /images/type-jboss.svg
globalMemoryLimit: 3698Mi
